### ISSUE TITLE
patreon button does not work

### ISSUE THREAD

**Issue by sudocode1** [dogegarden/dogetracker#16]
reference image
![image](https://user-images.githubusercontent.com/52894745/114224934-a4c63100-9969-11eb-9393-79bad2deaea3.png)

how to recreate
- go to [stats.dogehouse.xyz](https://stats.dogehouse.xyz)
- scroll down to the bottom to find the patreon box
- try clicking the patreon button

errors in console
none

i would make a pr for this but i dont know where the file to edit is

**Comment by s3ansh33p** [comment]
Noted, fill push a fix today.

**Comment by crispyaus** [comment]
fixed #18
